### PR TITLE
adding script for generating rungroups with datetime, and edited crea…

### PR DESCRIPTION
**Pull request by CameronHenshaw**
adding script for generating rungroups with datetime, and edited create_etl_rungroup.

### CODE REVIEW

**Comment by ejaxon** [comment]
Overall looks good. The one thing might be worth changing is line 77, in the rounder() function. Rather than round, maybe we should use math.floor or math.trunc to make sure we're using the previous time (and set the event run to run 1-2 minutes into the 15 minute period.

**Comment by bitslayer42** [comment]
create_run_map_function takes an optional param 'time' but it is not passed in from the event?

**Comment by bitslayer42** [comment]
I haven't followed the logic all the way, but did you test get_rungroup_matches at 14:30 minutes? Wondering if it should be 14 minutes and 59 seconds. And 999 milliseconds.

end_date = start_date + timedelta(minutes=14)

**Comment by CameronHenshaw** [comment]
So maybe I should remove the optional time param- I was using it for testing, and thought I might as well keep it in case we wanted to run the function to create rungroups that would normally run at specific times (even when it isn't currently that time). Maybe not really needed- let me know what you think.

I'm trying to remember why we picked 14 mins, because I remember talking to Eric about it, and I'm blanking. Eric, do you remember a specific, or would it be better to go ahead and change a more exact time interval?

**Comment by ejaxon** [comment]
Agree with removing the time parameter if it's only for testing purposes.

Re: 14, should probably be 14:59 or something. Given that AWS doesn't guarantee finer-than-minute granularity, we should not be putting sub-minute cron specifications at all, especially not ones that *also* fall at the boundary of the granularity of our checking.

Though of course this also violates the rule about magic numbers. Probably should define it somewhere in the file together with a comment about why it's 14:59 and not 14:59:9999.

**Comment by CameronHenshaw** [comment]
I took out the time parameter, and made it so you can change the time interval in just one place. 
I changed "math.floor" back to "round" per conversation with Eric.
The time delta is now based one second less than the time interval.

**Review by ejaxon — COMMENTED** [review]
This is a bigger change than I was expecting since I think it now only uses an incoming ```run_group``` parameter to *add* the rungroup to any that come out from the schedule, rather than allowing you to run either in the old mode (specify a rungroup) or in the new (pull rungroups by schedule). Am I missing something? I don't think the mixed mode is actually something we want.

The other thing that should be changed is line 20, setting WORKINGDIR to '.'. The current directory is not writable in a lambda - to write files it must be set to /tmp. If we want to make it easier for local testing, we should make it a parameter of the function and call from a local-testing function.

**Comment by CameronHenshaw** [comment]
You're not missing anything- I got in the weeds with a bug and took too much out. Fixed that, hopefully. 
Changed WORKINGDIR too.

**Review by ejaxon — APPROVED** [review]
Looks good to me.

**Comment by ejaxon** [comment]
Hey @CameronHenshaw I'm closing this because we had to rewrite create_etl_run_map in Javascript because of some build issues. I basically translated your code into JS as closely as I could.

**Pull request closed without merging**
